"use client";

import Image from "next/image";
import { ArrowUpRight, Award, BrainCircuit, Check, ChevronRight, Handshake, Linkedin, Menu, MessageCircle, PenTool, Play, Target, Twitch, X, Youtube } from "lucide-react";
import { useEffect, useState } from "react";

type Language = "es" | "en";
const copy = {
  es: {
    nav: [["Acerca", "#acerca"], ["Servicios", "#servicios"], ["Experiencia", "#experiencia"], ["Videos", "#videos"], ["Redes", "#redes"]],
    cta: "Agendar una llamada", heroKicker: "Arquitectura de software · IA · Liderazgo técnico", heroTitle: "Convierto complejidad tecnológica en decisiones claras.", heroText: "Acompaño a líderes y equipos a diseñar sistemas escalables, adoptar IA con criterio y transformar una visión ambiciosa en resultados concretos.", heroSecondary: "Conocer mi experiencia", proof: ["22+ años en tecnología", "Arquitectura y liderazgo", "Consultoría independiente"], portraitNote: "Montevideo · trabajando globalmente",
    metrics: [["22+", "años construyendo software"], ["14", "años formando profesionales"], ["2011", "1.er premio nacional de tesis maestría"], ["2", "publicaciones sobre mejora de procesos"]],
    aboutEyebrow: "Acerca de mí", aboutTitle: "Experiencia técnica para conectar estrategia, procesos y tecnología.", aboutBody: ["Soy ingeniero de software con más de 22 años de experiencia y una Maestría en Ingeniería (por investigación), enfocada en la mejora de procesos de software. Mi trabajo académico sobre análisis causal de defectos (DCA) mediante ontologías obtuvo el primer lugar en el Concurso Nacional de Tesis de Maestría de Uruguay en 2011.", "Como consultor independiente, ayudo a las organizaciones a conectar estrategia y tecnología. Aporto experiencia en mejora de procesos, aseguramiento de la calidad y ejecución de proyectos, siempre con foco en la eficiencia y en resultados escalables.", "Me apasionan la tecnología, el liderazgo de equipos y la mentoría para impulsar el crecimiento técnico y personal de otros profesionales. Actualmente, mis intereses también incluyen IA, automatización y la construcción de soluciones que potencien a equipos y organizaciones. Especialidades: mejora de procesos de software, gestión de proyectos y operaciones, desarrollo de productos de software, liderazgo de equipos, IA y automatización, capacitación y desarrollo."],
    awardLabel: "Investigación reconocida", awardTitle: "Primer premio nacional a tesis de maestría · 2011", awardText: "Mi investigación propuso OntoDCA, un enfoque basado en ontologías para capturar y reutilizar conocimiento causal sobre defectos de software.", awardSource: "Maestría en Ingeniería, Universidad ORT Uruguay",
    servicesEyebrow: "Cómo puedo ayudar", servicesTitle: "Tecnología aplicada a desafíos reales.", servicesText: "Intervenciones concretas para ordenar, decidir y avanzar.", services: [["01", "Desarrollos a medida IA-first", "Diseño y construcción de soluciones a medida que integran inteligencia artificial desde su concepción para potenciar productos, procesos y equipos."], ["02", "IA y automatización", "Identificación de casos de uso, validación técnica y adopción responsable sin sumar complejidad innecesaria."], ["03", "Liderazgo y ejecución", "Acompañamiento a equipos, roadmaps técnicos y decisiones que equilibran impacto, riesgo y velocidad."], ["04", "Arquitectura de software", "Diseño y evolución de sistemas escalables, confiables y alineados con el crecimiento del negocio."]],
    processEyebrow: "Forma de trabajo", processTitle: "De tu desafío a una solución con ingenio.", process: [["Entender", "Objetivos, restricciones y contexto real."], ["Enfocar", "Oportunidades con impacto verificable."], ["Diseñar", "Arquitectura, prioridades y próximos pasos."], ["Acompañar", "Ejecución, aprendizaje y mejora continua."]],
    expEyebrow: "Experiencia reciente", expTitle: "Experiencia técnica con visión estratégica.", expText: "Los roles más recientes de una carrera que une arquitectura, delivery, consultoría y formación.", jobs: [["2018 — hoy", "Santiago Arreche & Asociados", "Consultor independiente", "Estrategia tecnológica, arquitectura, mejora de operaciones IT y soluciones end-to-end para organizaciones de distintas industrias."], ["2021 — 2025", "Howdy", "Principal Software Architect", "Arquitecturas escalables para compañías de Estados Unidos, mentoría de ingeniería y alineación entre roadmaps técnicos y objetivos de negocio."], ["2020 — 2021", "Hozho Software", "Co-fundador", "Construcción de una compañía remote-first y entrega de productos web y móviles para clientes locales e internacionales."], ["2013 — 2021", "Topaz", "Technical Lead → Software Factory Coordinator", "Liderazgo técnico, portfolio de proyectos, preventa y desarrollo de la oficina de gestión de proyectos."]],
    videosEyebrow: "El Rincón de Sarreche", videosTitle: "Tecnología, reflexiones y cosas de la vida.", videosText: "Ideas, experimentos y conversaciones sin filtros, sin poses y sin manual.", watch: "Visitar el canal",
    socialEyebrow: "Sigamos la conversación", socialTitle: "Cada canal, una forma distinta de compartir.", socials: [["LinkedIn", "Ideas sobre arquitectura, liderazgo e IA."], ["YouTube", "Charlas, análisis y experimentos."], ["Twitch", "Directos y sesiones técnicas."], ["TikTok", "Tecnología en formato breve."]],
    finalEyebrow: "¿Hablamos?", finalTitle: "Si la tecnología es parte del desafío, hagamos que también sea parte de la solución.", finalText: "Una primera conversación para entender el contexto, ordenar posibilidades y decidir si tiene sentido avanzar juntos.", footer: "Arquitectura de software, IA y liderazgo técnico con criterio.", rights: "Todos los derechos reservados.",
  },
  en: {
    nav: [["About", "#acerca"], ["Services", "#servicios"], ["Experience", "#experiencia"], ["Videos", "#videos"], ["Social", "#redes"]],
    cta: "Book a call", heroKicker: "Software architecture · AI · Technical leadership", heroTitle: "I turn technological complexity into clear decisions.", heroText: "I help leaders and teams design scalable systems, adopt AI thoughtfully, and turn ambitious visions into concrete results.", heroSecondary: "Explore my experience", proof: ["22+ years in technology", "Architecture & leadership", "Independent consulting"], portraitNote: "Montevideo · working globally",
    metrics: [["22+", "years building software"], ["14", "years teaching professionals"], ["2011", "1st place national thesis award"], ["2", "publications on process improvement"]],
    aboutEyebrow: "About me", aboutTitle: "Technical experience connecting strategy, processes, and technology.", aboutBody: ["I am a Software Engineer with 22+ years of experience and a Master’s in Engineering (by Research) focused on software process improvement. My academic work on defect causal analysis (DCA) using ontologies was awarded first place in Uruguay’s National Master’s Thesis Competition (2011).", "As an independent consultant, I help organizations bridge the gap between strategy and technology. I bring expertise in process improvement, quality assurance, and project execution, always with a focus on efficiency and scalable results.", "I am passionate about technology, team leadership, and mentoring—supporting professionals to grow both technically and personally. Today, my interests also include AI, automation, and building solutions that empower teams and organizations. Specialties: Software Process Improvement | Project & Operations Management | Software Product Development | Team Leadership | AI & Automation | Training & Development"],
    awardLabel: "Recognized research", awardTitle: "First place, National Master’s Thesis Competition · 2011", awardText: "My research introduced OntoDCA, an ontology-driven approach for capturing and reusing causal knowledge about software defects.", awardSource: "Master of Engineering, Universidad ORT Uruguay",
    servicesEyebrow: "How I can help", servicesTitle: "Technology with a business reason behind it.", servicesText: "Focused engagements to bring clarity, make decisions, and move forward.", services: [["01", "Custom AI-first development", "Designing and building tailored solutions that integrate artificial intelligence from the start to strengthen products, processes, and teams."], ["02", "AI & automation", "Finding use cases, validating feasibility, and enabling responsible adoption without needless complexity."], ["03", "Leadership & execution", "Supporting teams, technical roadmaps, and decisions that balance impact, risk, and speed."], ["04", "Software architecture", "Designing and evolving scalable, reliable systems aligned with business growth."]],
    processEyebrow: "How I work", processTitle: "From your challenge to an ingenious solution.", process: [["Understand", "Goals, constraints, and the real context."], ["Focus", "Opportunities with verifiable impact."], ["Design", "Architecture, priorities, and next steps."], ["Partner", "Execution, learning, and continuous improvement."]],
    expEyebrow: "Recent experience", expTitle: "Technical depth with a business perspective.", expText: "The latest roles in a career spanning architecture, delivery, consulting, and education.", jobs: [["2018 — present", "Santiago Arreche & Associates", "Independent consultant", "Technology strategy, architecture, IT operations improvement, and end-to-end solutions across industries."], ["2021 — 2025", "Howdy", "Principal Software Architect", "Scalable architectures for U.S. companies, engineering mentorship, and alignment between technical roadmaps and business goals."], ["2020 — 2021", "Hozho Software", "Co-founder", "Built a remote-first company delivering web and mobile products to local and international clients."], ["2013 — 2021", "Topaz", "Technical Lead → Software Factory Coordinator", "Technical leadership, project portfolio management, pre-sales, and PMO development."]],
    videosEyebrow: "El Rincón de Sarreche", videosTitle: "Technology, reflections, and life beyond the screen.", videosText: "Ideas, experiments, and conversations — no filters, no posing, no manual.", watch: "Visit the channel",
    socialEyebrow: "Keep the conversation going", socialTitle: "A different way to share on every channel.", socials: [["LinkedIn", "Ideas on architecture, leadership, and AI."], ["YouTube", "Talks, analysis, and experiments."], ["Twitch", "Live conversations and technical sessions."], ["TikTok", "Technology in a shorter format."]],
    finalEyebrow: "Let’s talk", finalTitle: "If technology is part of the challenge, let’s make it part of the solution.", finalText: "A first conversation to understand the context, map the possibilities, and see whether working together makes sense.", footer: "Software architecture, AI, and technical leadership with judgment.", rights: "All rights reserved.",
  },
} as const;

const socialLinks = { LinkedIn: "https://www.linkedin.com/in/sarreche", YouTube: "https://www.youtube.com/@saarreche", Twitch: "https://www.twitch.tv/sarreche", TikTok: "https://www.tiktok.com/@bysarreche" };
const socialIcons = { LinkedIn: Linkedin, YouTube: Youtube, Twitch, TikTok: Play };
const bookingUrl = "https://calendly.com/sarreche/sarreche";

export default function Home() {
  const [lang, setLang] = useState<Language>("es");
  const [menuOpen, setMenuOpen] = useState(false);
  const t = copy[lang];
  useEffect(() => { document.documentElement.lang = lang; }, [lang]);
  return <div className="site-shell">
    <header className="nav-wrap"><nav className="nav" aria-label={lang === "es" ? "Navegación principal" : "Main navigation"}>
      <a href="#inicio" className="wordmark" aria-label="Ing. Santiago Arreche, inicio"><span className="brand-mark" aria-hidden="true"><BrainCircuit size={19} /></span><strong>Ing. Santiago Arreche</strong></a>
      <div className="nav-links">{t.nav.map(([label, href]) => <a key={href} href={href}>{label}</a>)}</div>
      <div className="nav-actions"><div className="language-switch" aria-label={lang === "es" ? "Seleccionar idioma" : "Select language"}><button className={lang === "es" ? "active" : ""} onClick={() => setLang("es")} aria-pressed={lang === "es"}>ES</button><button className={lang === "en" ? "active" : ""} onClick={() => setLang("en")} aria-pressed={lang === "en"}>EN</button></div><a className="button button-small" href={bookingUrl} target="_blank" rel="noreferrer">{t.cta}<ArrowUpRight size={16} /></a><button className="menu-button" onClick={() => setMenuOpen(!menuOpen)} aria-label={menuOpen ? "Cerrar menú" : "Abrir menú"}>{menuOpen ? <X /> : <Menu />}</button></div>
    </nav>{menuOpen && <div className="mobile-menu">{t.nav.map(([label, href]) => <a key={href} href={href} onClick={() => setMenuOpen(false)}>{label}</a>)}<a className="button" href={bookingUrl} target="_blank" rel="noreferrer">{t.cta}</a></div>}</header>
    <main>
      <section id="inicio" className="hero section-pad"><div className="hero-copy"><p className="eyebrow">{t.heroKicker}</p><h1>{t.heroTitle}</h1><p className="hero-lead">{t.heroText}</p><div className="hero-actions"><a className="button" href={bookingUrl} target="_blank" rel="noreferrer">{t.cta}<ArrowUpRight size={18} /></a><a className="text-link" href="#experiencia">{t.heroSecondary}<ChevronRight size={17} /></a></div><div className="proof-row">{t.proof.map((item) => <span key={item}><Check size={14} />{item}</span>)}</div></div><div className="hero-visual"><div className="portrait-frame"><Image src="/images/santiago-portrait.jpg" alt="Ing. Santiago Arreche" fill priority sizes="(min-width: 900px) 42vw, 90vw" className="portrait" /></div><div className="portrait-card"><span className="status-dot" /><div><strong>Ing. Santiago Arreche</strong><p>{t.portraitNote}</p></div></div><div className="blue-stroke" aria-hidden="true" /></div></section>
      <section className="metrics" aria-label={lang === "es" ? "Credenciales" : "Credentials"}>{t.metrics.map(([value, label]) => <div key={label}><strong>{value}</strong><span>{label}</span></div>)}</section>
      <section id="acerca" className="about section-pad"><div className="section-intro"><p className="eyebrow">{t.aboutEyebrow}</p><h2>{t.aboutTitle}</h2></div><div className="about-copy">{t.aboutBody.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}</div><article className="award-card"><Award size={28} /><div><p className="award-label">{t.awardLabel}</p><h3>{t.awardTitle}</h3><p>{t.awardText}</p><span>{t.awardSource}</span></div></article></section>
      <section id="servicios" className="dark-section section-pad"><div className="section-heading-row"><div><p className="eyebrow">{t.servicesEyebrow}</p><h2>{t.servicesTitle}</h2></div><p>{t.servicesText}</p></div><div className="service-grid">{t.services.map(([number, title, text]) => <article key={number}><span>{number}</span><BrainCircuit size={25} /><h3>{title}</h3><p>{text}</p></article>)}</div></section>
      <section id="proceso" className="process section-pad"><div className="section-intro"><p className="eyebrow">{t.processEyebrow}</p><h2>{t.processTitle}</h2></div><div className="process-grid">{t.process.map(([title, text], index) => { const Icon = [MessageCircle, Target, PenTool, Handshake][index]; return <article key={title}><span className="process-icon" aria-hidden="true"><Icon size={22} strokeWidth={1.8} /></span><h3>{title}</h3><p>{text}</p></article>; })}</div></section>
      <section id="experiencia" className="experience section-pad"><div className="section-heading-row"><div><p className="eyebrow">{t.expEyebrow}</p><h2>{t.expTitle}</h2></div><p>{t.expText}</p></div><div className="timeline">{t.jobs.map(([date, company, role, text], index) => <article key={company}><div className="timeline-date">{date}</div><div className="timeline-marker"><span>{index + 1}</span></div><div className="timeline-body"><p>{company}</p><h3>{role}</h3><span>{text}</span></div></article>)}</div></section>
      <section id="videos" className="channel section-pad"><div className="channel-image"><Image src="/images/youtube-channel.png" alt="Canal de YouTube El Rincón de Sarreche" fill sizes="(min-width: 900px) 52vw, 100vw" className="cover" /></div><div className="channel-copy"><p className="eyebrow">{t.videosEyebrow}</p><h2>{t.videosTitle}</h2><p>{t.videosText}</p><a className="button button-light" href={socialLinks.YouTube} target="_blank" rel="noreferrer"><Youtube size={18} />{t.watch}<ArrowUpRight size={17} /></a></div></section>
      <section id="redes" className="social section-pad"><div className="section-intro"><p className="eyebrow">{t.socialEyebrow}</p><h2>{t.socialTitle}</h2></div><div className="social-grid">{t.socials.map(([name, text]) => { const Icon = socialIcons[name as keyof typeof socialIcons]; return <a key={name} href={socialLinks[name as keyof typeof socialLinks]} target="_blank" rel="noreferrer"><Icon size={23} /><div><strong>{name}</strong><p>{text}</p></div><ArrowUpRight className="social-arrow" size={18} /></a>; })}</div></section>
      <section className="final-cta section-pad"><p className="eyebrow">{t.finalEyebrow}</p><h2>{t.finalTitle}</h2><p>{t.finalText}</p><a className="button button-light" href={bookingUrl} target="_blank" rel="noreferrer">{t.cta}<ArrowUpRight size={18} /></a></section>
    </main>
    <footer><div><a href="#inicio" className="wordmark"><span className="brand-mark" aria-hidden="true"><BrainCircuit size={19} /></span><strong>Ing. Santiago Arreche</strong></a><p>{t.footer}</p></div><div className="footer-links">{t.nav.map(([label, href]) => <a key={href} href={href}>{label}</a>)}</div><p className="copyright">© {new Date().getFullYear()} Santiago Arreche. {t.rights}</p></footer>
  </div>;
}
